Gas limit error in script10
10-create-vote proposals.js fails with a gas limit error if the minimumNumberOfTokensNeededToPropose value in 8-deploy-vote.js is something other than 0. Kinda hard to catch the bug since 8 and 9 run successfully but 10 fails. We need to add something to warn people about this.

Error: cannot estimate gas; transaction may fail or may require manual gas limit